<?php

/**
* Implements hook_nodeapi().
*/
function ldiw_activity_nodeapi(&$node, $op) {
  global $user;
  if ($node->type ==  'waste_point') {
    $fbid = fboauth_fbid_load($node->uid);
    if ($fbid) {
      switch ($op) {
        case 'insert':
          $message = $user->name . ' added a wastepoint';
          break;

        case 'update':
          $message = $user->name . ' updated a wastepoint';
          break;
      }
       //dsm($context);
      if (isset($message)) {
        $data['uid'] = $node->uid;
        $data['reference_nid'] = $node->nid;
        //print_r($node);
        ldiw_activity_create_entry($data, $op, $message);
      }
    }
  }
}

/**
* @param $data Contain current user uid, longitude and lattitude.
* @param $type Activity type.
* @param $message Activity message.
*/
function ldiw_activity_create_entry($data = array(), $type = '', $message = '') {
  $node = new stdClass();
  $node->title = $message;
  $node->type = "ldiw_activity";
  $node->uid = $data['uid'];
  // node_object_prepare($node);
  $node->language = ''; // Or e.g. 'en' if locale is enabled
  $node->uid =  $data['uid'];
  $node->status = 0; //(1 or 0): published or not
  $node->promote = 0; //(1 or 0): promoted to front page
  $node->comment = 1; //2 = comments on, 1 = comments
  if(!empty($data['lon']) && !empty($data['lat'])) {
    $node->field_coordinates[0]['geo']['lon'] = $data['lon'];
    $node->field_coordinates[0]['geo']['lat'] = $data['lat'];
  }
  if (isset($data['reference_nid'])){
    $node->field_added_node_ref[0]['nid'] = $data['reference_nid'];
  }
  $node->field_event_type[0]['value'] = $type;
  $node = node_submit($node); // Prepare node for saving
  node_save($node);
}
